export const colors = {
  icon: {
    DEFAULT: "hsl(var(--colors-icon-default))",
    disabled: "hsl(var(--colors-icon-disabled))",
    muted: "hsl(var(--colors-icon-muted))",
    inverse: "hsl(var(--colors-icon-inverse))",
    oncolor: "hsl(var(--colors-icon-oncolor))",
    primary: "hsl(var(--colors-icon-primary))",
    success: "hsl(var(--colors-icon-success))",
    error: "hsl(var(--colors-icon-error))",
    warning: "hsl(var(--colors-icon-warning))",
    info: "hsl(var(--colors-icon-info))",
    interactive: "hsl(var(--colors-icon-interactive))",
    magic: "hsl(var(--colors-icon-magic))",
  },
  base: {
    white: "hsl(var(--colors-base-white))",
    black: "hsl(var(--colors-base-black))",
  },
  slate: {
    "50": "hsl(var(--colors-slate-50))",
    "100": "hsl(var(--colors-slate-100))",
    "200": "hsl(var(--colors-slate-200))",
    "300": "hsl(var(--colors-slate-300))",
    "400": "hsl(var(--colors-slate-400))",
    "500": "hsl(var(--colors-slate-500))",
    "600": "hsl(var(--colors-slate-600))",
    "700": "hsl(var(--colors-slate-700))",
    "800": "hsl(var(--colors-slate-800))",
    "900": "hsl(var(--colors-slate-900))",
    "950": "hsl(var(--colors-slate-950))",
  },
  gray: {
    "50": "hsl(var(--colors-gray-50))",
    "100": "hsl(var(--colors-gray-100))",
    "200": "hsl(var(--colors-gray-200))",
    "300": "hsl(var(--colors-gray-300))",
    "400": "hsl(var(--colors-gray-400))",
    "500": "hsl(var(--colors-gray-500))",
    "600": "hsl(var(--colors-gray-600))",
    "700": "hsl(var(--colors-gray-700))",
    "800": "hsl(var(--colors-gray-800))",
    "900": "hsl(var(--colors-gray-900))",
    "950": "hsl(var(--colors-gray-950))",
  },
  zinc: {
    "50": "hsl(var(--colors-zinc-50))",
    "100": "hsl(var(--colors-zinc-100))",
    "200": "hsl(var(--colors-zinc-200))",
    "300": "hsl(var(--colors-zinc-300))",
    "400": "hsl(var(--colors-zinc-400))",
    "500": "hsl(var(--colors-zinc-500))",
    "600": "hsl(var(--colors-zinc-600))",
    "700": "hsl(var(--colors-zinc-700))",
    "800": "hsl(var(--colors-zinc-800))",
    "900": "hsl(var(--colors-zinc-900))",
    "950": "hsl(var(--colors-zinc-950))",
  },
  neutral: {
    "50": "hsl(var(--colors-neutral-50))",
    "100": "hsl(var(--colors-neutral-100))",
    "200": "hsl(var(--colors-neutral-200))",
    "300": "hsl(var(--colors-neutral-300))",
    "400": "hsl(var(--colors-neutral-400))",
    "500": "hsl(var(--colors-neutral-500))",
    "600": "hsl(var(--colors-neutral-600))",
    "700": "hsl(var(--colors-neutral-700))",
    "800": "hsl(var(--colors-neutral-800))",
    "900": "hsl(var(--colors-neutral-900))",
    "950": "hsl(var(--colors-neutral-950))",
  },
  stone: {
    "50": "hsl(var(--colors-stone-50))",
    "100": "hsl(var(--colors-stone-100))",
    "200": "hsl(var(--colors-stone-200))",
    "300": "hsl(var(--colors-stone-300))",
    "400": "hsl(var(--colors-stone-400))",
    "500": "hsl(var(--colors-stone-500))",
    "600": "hsl(var(--colors-stone-600))",
    "700": "hsl(var(--colors-stone-700))",
    "800": "hsl(var(--colors-stone-800))",
    "900": "hsl(var(--colors-stone-900))",
    "950": "hsl(var(--colors-stone-950))",
  },
  red: {
    "50": "hsl(var(--colors-red-50))",
    "100": "hsl(var(--colors-red-100))",
    "200": "hsl(var(--colors-red-200))",
    "300": "hsl(var(--colors-red-300))",
    "400": "hsl(var(--colors-red-400))",
    "500": "hsl(var(--colors-red-500))",
    "600": "hsl(var(--colors-red-600))",
    "700": "hsl(var(--colors-red-700))",
    "800": "hsl(var(--colors-red-800))",
    "900": "hsl(var(--colors-red-900))",
    "950": "hsl(var(--colors-red-950))",
  },
  orange: {
    "50": "hsl(var(--colors-orange-50))",
    "100": "hsl(var(--colors-orange-100))",
    "200": "hsl(var(--colors-orange-200))",
    "300": "hsl(var(--colors-orange-300))",
    "400": "hsl(var(--colors-orange-400))",
    "500": "hsl(var(--colors-orange-500))",
    "600": "hsl(var(--colors-orange-600))",
    "700": "hsl(var(--colors-orange-700))",
    "800": "hsl(var(--colors-orange-800))",
    "900": "hsl(var(--colors-orange-900))",
    "950": "hsl(var(--colors-orange-950))",
  },
  amber: {
    "50": "hsl(var(--colors-amber-50))",
    "100": "hsl(var(--colors-amber-100))",
    "200": "hsl(var(--colors-amber-200))",
    "300": "hsl(var(--colors-amber-300))",
    "400": "hsl(var(--colors-amber-400))",
    "500": "hsl(var(--colors-amber-500))",
    "600": "hsl(var(--colors-amber-600))",
    "700": "hsl(var(--colors-amber-700))",
    "800": "hsl(var(--colors-amber-800))",
    "900": "hsl(var(--colors-amber-900))",
    "950": "hsl(var(--colors-amber-950))",
  },
  lime: {
    "50": "hsl(var(--colors-lime-50))",
    "100": "hsl(var(--colors-lime-100))",
    "200": "hsl(var(--colors-lime-200))",
    "300": "hsl(var(--colors-lime-300))",
    "400": "hsl(var(--colors-lime-400))",
    "500": "hsl(var(--colors-lime-500))",
    "600": "hsl(var(--colors-lime-600))",
    "700": "hsl(var(--colors-lime-700))",
    "800": "hsl(var(--colors-lime-800))",
    "900": "hsl(var(--colors-lime-900))",
    "950": "hsl(var(--colors-lime-950))",
  },
  yellow: {
    "50": "hsl(var(--colors-yellow-50))",
    "100": "hsl(var(--colors-yellow-100))",
    "200": "hsl(var(--colors-yellow-200))",
    "300": "hsl(var(--colors-yellow-300))",
    "400": "hsl(var(--colors-yellow-400))",
    "500": "hsl(var(--colors-yellow-500))",
    "600": "hsl(var(--colors-yellow-600))",
    "700": "hsl(var(--colors-yellow-700))",
    "800": "hsl(var(--colors-yellow-800))",
    "900": "hsl(var(--colors-yellow-900))",
    "950": "hsl(var(--colors-yellow-950))",
  },
  green: {
    "50": "hsl(var(--colors-green-50))",
    "100": "hsl(var(--colors-green-100))",
    "200": "hsl(var(--colors-green-200))",
    "300": "hsl(var(--colors-green-300))",
    "400": "hsl(var(--colors-green-400))",
    "500": "hsl(var(--colors-green-500))",
    "600": "hsl(var(--colors-green-600))",
    "700": "hsl(var(--colors-green-700))",
    "800": "hsl(var(--colors-green-800))",
    "900": "hsl(var(--colors-green-900))",
    "950": "hsl(var(--colors-green-950))",
  },
  emerald: {
    "50": "hsl(var(--colors-emerald-50))",
    "100": "hsl(var(--colors-emerald-100))",
    "200": "hsl(var(--colors-emerald-200))",
    "300": "hsl(var(--colors-emerald-300))",
    "400": "hsl(var(--colors-emerald-400))",
    "500": "hsl(var(--colors-emerald-500))",
    "600": "hsl(var(--colors-emerald-600))",
    "700": "hsl(var(--colors-emerald-700))",
    "800": "hsl(var(--colors-emerald-800))",
    "900": "hsl(var(--colors-emerald-900))",
    "950": "hsl(var(--colors-emerald-950))",
  },
  teal: {
    "50": "hsl(var(--colors-teal-50))",
    "100": "hsl(var(--colors-teal-100))",
    "200": "hsl(var(--colors-teal-200))",
    "300": "hsl(var(--colors-teal-300))",
    "400": "hsl(var(--colors-teal-400))",
    "500": "hsl(var(--colors-teal-500))",
    "600": "hsl(var(--colors-teal-600))",
    "700": "hsl(var(--colors-teal-700))",
    "800": "hsl(var(--colors-teal-800))",
    "900": "hsl(var(--colors-teal-900))",
    "950": "hsl(var(--colors-teal-950))",
  },
  cyan: {
    "50": "hsl(var(--colors-cyan-50))",
    "100": "hsl(var(--colors-cyan-100))",
    "200": "hsl(var(--colors-cyan-200))",
    "300": "hsl(var(--colors-cyan-300))",
    "400": "hsl(var(--colors-cyan-400))",
    "500": "hsl(var(--colors-cyan-500))",
    "600": "hsl(var(--colors-cyan-600))",
    "700": "hsl(var(--colors-cyan-700))",
    "800": "hsl(var(--colors-cyan-800))",
    "900": "hsl(var(--colors-cyan-900))",
    "950": "hsl(var(--colors-cyan-950))",
  },
  sky: {
    "50": "hsl(var(--colors-sky-50))",
    "100": "hsl(var(--colors-sky-100))",
    "200": "hsl(var(--colors-sky-200))",
    "300": "hsl(var(--colors-sky-300))",
    "400": "hsl(var(--colors-sky-400))",
    "500": "hsl(var(--colors-sky-500))",
    "600": "hsl(var(--colors-sky-600))",
    "700": "hsl(var(--colors-sky-700))",
    "800": "hsl(var(--colors-sky-800))",
    "900": "hsl(var(--colors-sky-900))",
    "950": "hsl(var(--colors-sky-950))",
  },
  blue: {
    "50": "hsl(var(--colors-blue-50))",
    "100": "hsl(var(--colors-blue-100))",
    "200": "hsl(var(--colors-blue-200))",
    "300": "hsl(var(--colors-blue-300))",
    "400": "hsl(var(--colors-blue-400))",
    "500": "hsl(var(--colors-blue-500))",
    "600": "hsl(var(--colors-blue-600))",
    "700": "hsl(var(--colors-blue-700))",
    "800": "hsl(var(--colors-blue-800))",
    "900": "hsl(var(--colors-blue-900))",
    "950": "hsl(var(--colors-blue-950))",
  },
  indigo: {
    "50": "hsl(var(--colors-indigo-50))",
    "100": "hsl(var(--colors-indigo-100))",
    "200": "hsl(var(--colors-indigo-200))",
    "300": "hsl(var(--colors-indigo-300))",
    "400": "hsl(var(--colors-indigo-400))",
    "500": "hsl(var(--colors-indigo-500))",
    "600": "hsl(var(--colors-indigo-600))",
    "700": "hsl(var(--colors-indigo-700))",
    "800": "hsl(var(--colors-indigo-800))",
    "900": "hsl(var(--colors-indigo-900))",
    "950": "hsl(var(--colors-indigo-950))",
  },
  violet: {
    "50": "hsl(var(--colors-violet-50))",
    "100": "hsl(var(--colors-violet-100))",
    "200": "hsl(var(--colors-violet-200))",
    "300": "hsl(var(--colors-violet-300))",
    "400": "hsl(var(--colors-violet-400))",
    "500": "hsl(var(--colors-violet-500))",
    "600": "hsl(var(--colors-violet-600))",
    "700": "hsl(var(--colors-violet-700))",
    "800": "hsl(var(--colors-violet-800))",
    "900": "hsl(var(--colors-violet-900))",
    "950": "hsl(var(--colors-violet-950))",
  },
  purple: {
    "50": "hsl(var(--colors-purple-50))",
    "100": "hsl(var(--colors-purple-100))",
    "200": "hsl(var(--colors-purple-200))",
    "300": "hsl(var(--colors-purple-300))",
    "400": "hsl(var(--colors-purple-400))",
    "500": "hsl(var(--colors-purple-500))",
    "600": "hsl(var(--colors-purple-600))",
    "700": "hsl(var(--colors-purple-700))",
    "800": "hsl(var(--colors-purple-800))",
    "900": "hsl(var(--colors-purple-900))",
    "950": "hsl(var(--colors-purple-950))",
  },
  fuchsia: {
    "50": "hsl(var(--colors-fuchsia-50))",
    "100": "hsl(var(--colors-fuchsia-100))",
    "200": "hsl(var(--colors-fuchsia-200))",
    "300": "hsl(var(--colors-fuchsia-300))",
    "400": "hsl(var(--colors-fuchsia-400))",
    "500": "hsl(var(--colors-fuchsia-500))",
    "600": "hsl(var(--colors-fuchsia-600))",
    "700": "hsl(var(--colors-fuchsia-700))",
    "800": "hsl(var(--colors-fuchsia-800))",
    "900": "hsl(var(--colors-fuchsia-900))",
    "950": "hsl(var(--colors-fuchsia-950))",
  },
  pink: {
    "50": "hsl(var(--colors-pink-50))",
    "100": "hsl(var(--colors-pink-100))",
    "200": "hsl(var(--colors-pink-200))",
    "300": "hsl(var(--colors-pink-300))",
    "400": "hsl(var(--colors-pink-400))",
    "500": "hsl(var(--colors-pink-500))",
    "600": "hsl(var(--colors-pink-600))",
    "700": "hsl(var(--colors-pink-700))",
    "800": "hsl(var(--colors-pink-800))",
    "900": "hsl(var(--colors-pink-900))",
    "950": "hsl(var(--colors-pink-950))",
  },
  rose: {
    "50": "hsl(var(--colors-rose-50))",
    "100": "hsl(var(--colors-rose-100))",
    "200": "hsl(var(--colors-rose-200))",
    "300": "hsl(var(--colors-rose-300))",
    "400": "hsl(var(--colors-rose-400))",
    "500": "hsl(var(--colors-rose-500))",
    "600": "hsl(var(--colors-rose-600))",
    "700": "hsl(var(--colors-rose-700))",
    "800": "hsl(var(--colors-rose-800))",
    "900": "hsl(var(--colors-rose-900))",
    "950": "hsl(var(--colors-rose-950))",
  },
};
export const backgroundColor = {
  DEFAULT: "hsl(var(--colors-bg-default))",
  subtle: "hsl(var(--colors-bg-subtle))",
  elevated: "hsl(var(--colors-bg-elevated))",
  strong: "hsl(var(--colors-bg-strong))",
  disabled: "hsl(var(--colors-bg-disabled))",
  inverse: "hsl(var(--colors-bg-inverse))",
  primary: {
    DEFAULT: "hsl(var(--colors-bg-primary-default))",
    hover: "hsl(var(--colors-bg-primary-hover))",
    active: "hsl(var(--colors-bg-primary-active))",
  },
  secondary: {
    DEFAULT: "hsl(var(--colors-bg-secondary-default))",
    hover: "hsl(var(--colors-bg-secondary-hover))",
    active: "hsl(var(--colors-bg-secondary-active))",
  },
  success: {
    strong: "hsl(var(--colors-bg-success-strong))",
    muted: {
      DEFAULT: "hsl(var(--colors-bg-success-muted-default))",
      hover: "hsl(var(--colors-bg-success-muted-hover))",
      active: "hsl(var(--colors-bg-success-muted-active))",
    },
  },
  error: {
    strong: {
      DEFAULT: "hsl(var(--colors-bg-error-strong-default))",
      hover: "hsl(var(--colors-bg-error-strong-hover))",
      active: "hsl(var(--colors-bg-error-strong-active))",
    },
    muted: {
      DEFAULT: "hsl(var(--colors-bg-error-muted-default))",
      hover: "hsl(var(--colors-bg-error-muted-hover))",
      active: "hsl(var(--colors-bg-error-muted-active))",
    },
  },
  warning: {
    strong: "hsl(var(--colors-bg-warning-strong))",
    muted: {
      DEFAULT: "hsl(var(--colors-bg-warning-muted-default))",
      hover: "hsl(var(--colors-bg-warning-muted-hover))",
      active: "hsl(var(--colors-bg-warning-muted-active))",
    },
  },
  info: {
    strong: "hsl(var(--colors-bg-info-strong))",
    muted: {
      DEFAULT: "hsl(var(--colors-bg-info-muted-default))",
      hover: "hsl(var(--colors-bg-info-muted-hover))",
      active: "hsl(var(--colors-bg-info-muted-active))",
    },
  },
  interactive: {
    DEFAULT: "hsl(var(--colors-bg-interactive-default))",
    hover: "hsl(var(--colors-bg-interactive-hover))",
    active: "hsl(var(--colors-bg-interactive-active))",
    muted: {
      DEFAULT: "hsl(var(--colors-bg-interactive-muted-default))",
      hover: "hsl(var(--colors-bg-interactive-muted-hover))",
      active: "hsl(var(--colors-bg-interactive-muted-active))",
    },
  },
  magic: {
    DEFAULT: "hsl(var(--colors-bg-magic-default))",
    hover: "hsl(var(--colors-bg-magic-hover))",
    active: "hsl(var(--colors-bg-magic-active))",
    muted: {
      DEFAULT: "hsl(var(--colors-bg-magic-muted-default))",
      hover: "hsl(var(--colors-bg-magic-muted-hover))",
      active: "hsl(var(--colors-bg-magic-muted-active))",
    },
  },
};

export const textColor = {
  DEFAULT: "hsl(var(--colors-text-default))",
  muted: "hsl(var(--colors-text-muted))",
  disabled: "hsl(var(--colors-text-disabled))",
  placeholder: "hsl(var(--colors-text-placeholder))",
  inverse: "hsl(var(--colors-text-inverse))",
  oncolor: "hsl(var(--colors-text-oncolor))",
  success: {
    DEFAULT: "hsl(var(--colors-text-success-default))",
    strong: "hsl(var(--colors-text-success-strong))",
  },
  primary: {
    DEFAULT: "hsl(var(--colors-text-primary-default))",
    hover: "hsl(var(--colors-text-primary-hover))",
  },
  error: {
    DEFAULT: "hsl(var(--colors-text-error-default))",
    strong: "hsl(var(--colors-text-error-strong))",
    active: "hsl(var(--colors-text-error-active))",
  },
  warning: {
    DEFAULT: "hsl(var(--colors-text-warning-default))",
    strong: "hsl(var(--colors-text-warning-strong))",
  },
  info: {
    DEFAULT: "hsl(var(--colors-text-info-default))",
    strong: "hsl(var(--colors-text-info-strong))",
  },
  interactive: {
    DEFAULT: "hsl(var(--colors-text-interactive-default))",
    strong: "hsl(var(--colors-text-interactive-strong))",
  },
  magic: {
    DEFAULT: "hsl(var(--colors-text-magic-default))",
    strong: "hsl(var(--colors-text-magic-strong))",
  },
};

export const borderColor = {
  DEFAULT: "hsl(var(--colors-border-default))",
  hover: "hsl(var(--colors-border-hover))",
  input: {
    DEFAULT: "hsl(var(--colors-border-input-default))",
    hover: "hsl(var(--colors-border-input-hover))",
  },
  disabled: "hsl(var(--colors-border-disabled))",
  oncolor: "hsl(var(--colors-border-oncolor))",
  primary: "hsl(var(--colors-border-primary))",
  success: {
    DEFAULT: "hsl(var(--colors-border-success-default))",
    muted: "hsl(var(--colors-border-success-muted))",
  },
  error: {
    DEFAULT: "hsl(var(--colors-border-error-default))",
    hover: "hsl(var(--colors-border-error-hover))",
    active: "hsl(var(--colors-border-error-active))",
    muted: "hsl(var(--colors-border-error-muted))",
  },
  warning: {
    DEFAULT: "hsl(var(--colors-border-warning-default))",
    muted: "hsl(var(--colors-border-warning-muted))",
  },
  info: {
    DEFAULT: "hsl(var(--colors-border-info-default))",
    muted: "hsl(var(--colors-border-info-muted))",
  },
  interactive: {
    DEFAULT: "hsl(var(--colors-border-interactive-default))",
    hover: "hsl(var(--colors-border-interactive-hover))",
    active: "hsl(var(--colors-border-interactive-active))",
    focus: "hsl(var(--colors-border-interactive-focus))",
  },
  focusring: "hsl(var(--colors-border-focusring))",
  magic: {
    DEFAULT: "hsl(var(--colors-border-magic-default))",
    muted: "hsl(var(--colors-border-magic-muted))",
  },
};
